### ISSUE TITLE
My license?

### ISSUE THREAD

**Issue by mattmassicotte** [tonyarnold/swift-openapi-foundation#1]
Hello Tony!

I noticed that you added my license to a few files, and I know this is a crazy question, but did I actually write those things?

**Comment by mattmassicotte** [comment]
One extension you might actually want to include is this one:

https://github.com/ChimeHQ/OAuthenticator/blob/main/Sources/OAuthenticator/URLSession%2BResponseProvider.swift

**Comment by tonyarnold** [comment]
You are absolutely right! I've copypasta'd your license in there instead of Apple's Apache license 😬 

Thanks for pointing that out!
